M48
; DRILL file KiCad 10.0.4 date 2026-08-18T14:15:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-18T14:15:18-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X122.03Y-103.575
X122.03Y-108.425
T2
X119.0Y-103.275
X119.0Y-108.725
M30
