"""Extract real PCM extrema for the silent Wave design study.

Run with a directory containing the four upstream MP3s documented in README.md.
Requires ffmpeg on PATH. The browser only needs the generated peak data.
"""

import array
import hashlib
import json
from pathlib import Path
import subprocess
import sys


def extract(source):
    pcm = subprocess.check_output([
        "ffmpeg", "-v", "error", "-i", str(source), "-ac", "1",
        "-ar", "44100", "-f", "f32le", "-",
    ])
    samples = array.array("f", pcm)
    if sys.byteorder != "little":
        samples.byteswap()
    peaks = []
    for i in range(1024):
        window = samples[i * len(samples) // 1024:(i + 1) * len(samples) // 1024]
        peaks.append([round(min(window) * 10000), round(max(window) * 10000)])
    return {
        "id": source.stem,
        "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "seconds": round(len(samples) / 44100, 5),
        "peaks": peaks,
    }


if __name__ == "__main__":
    source = Path(sys.argv[1])
    data = [extract(source / f"{name}.mp3") for name in
            ["leadguitar", "clav", "drums", "bassguitar"]]
    target = Path(__file__).with_name("peaks.js")
    target.write_text("// Generated by build_peaks.py from reference audio; see README.md.\n"
                      "window.segnoWaveformReferences=" + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"Extracted {len(data)} recordings, 1024 PCM min/max pairs each.")
